# Generated by Django 3.0.2 on 2020-02-19 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Enter your email')),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=100, unique=True, verbose_name='Contact_Number')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='department.Department')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salary', to='salary.Salary')),
            ],
        ),
    ]
