# Generated by Django 3.0.2 on 2020-02-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_job', models.CharField(max_length=200)),
                ('sal_type', models.CharField(max_length=200)),
                ('sal_amt', models.FloatField(verbose_name='Enter Amount')),
                ('sal_description', models.TextField(blank=True)),
            ],
        ),
    ]
