# Generated by Django 3.0.2 on 2020-02-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('demail', models.EmailField(max_length=254, unique=True, verbose_name='Enter your email')),
                ('daddress', models.CharField(max_length=200, verbose_name='Department Address')),
                ('description', models.TextField(blank=True)),
                ('dcontact', models.CharField(max_length=100, unique=True, verbose_name='Contact_Number')),
            ],
        ),
    ]
